hse_programs = {
    'москва': {
        'Актер': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Akter_O.xlsx',
        'Античность (История)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Ant_Ist_O.xlsx',
        'Античность (Филология)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Ant_Fil_O.xlsx',
        'Ассириология: языки и история древней Месопотамии': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Assir_O.xlsx',
        'Бизнес-информатика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_BI_O.xlsx',
        'Востоковедение': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Vostok_O.xlsx',
        'География глобальных изменений и геоинформационные технологии': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GGIGT_O.xlsx',
        'Глобальные цифровые коммуникации (Медиакоммуникации)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GlDComM_O.xlsx',
        'Глобальные цифровые коммуникации (Реклама и связи с общественностью)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GlDCom_O.xlsx',
        'Городское планирование': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GorPlan_O.xlsx',
        'Государственное и муниципальное управление': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GMU_O.xlsx',
        'Дизайн': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Design_O.xlsx',
        'Дизайн и разработка информационных продуктов': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_DisDevInfP_O.xlsx',
        'Журналистика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ZHur_O.xlsx',
        'Иностранные языки и межкультурная коммуникация': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_IYAMK_O.xlsx',
        'Инфокоммуникационные технологии и системы связи': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ITSS_O.xlsx',
        'Информатика и вычислительная техника': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_IVT_O.xlsx',
        'Информационная безопасность': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_IB_O.xlsx',
        'История': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ISTR_O.xlsx',
        'История искусств': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Isk_O.xlsx',
        'Кинопроизводство': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Film_O.xlsx',
        'Клеточная и молекулярная биотехнология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_CMB_O.xlsx',
        'Когнитивная нейробиология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_KogNeir_O.xlsx',
        'Компьютерная безопасность': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_KB_O.xlsx',
        'Компьютерные науки и анализ данных': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Compds_O.xlsx',
        'Культурология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Cultural_O.xlsx',
        'Маркетинг и рыночная аналитика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Marketing_O.xlsx',
        'Математика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Math_O.xlsx',
        'Медиакоммуникации': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Media_O.xlsx',
        'Международная программа "Международные отношения и глобальные исследования" (Международные отношения)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_irmo_O.xlsx',
        'Международная программа "Международные отношения и глобальные исследования" (Публичная политика и социальные науки)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_irpp_O.xlsx',
        'Международная программа по экономике и финансам': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_icef_O.xlsx',
        'Международные отношения': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_MO_O.xlsx',
        'Международный бизнес': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_MB_O.xlsx',
        'Мировая экономика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_WE_O.xlsx',
        'Мода': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Moda_O.xlsx',
        'Политология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Political_O.xlsx',
        'Прикладная математика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_AM_O.xlsx',
        'Прикладная математика и информатика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_AMI_O.xlsx',
        'Прикладной анализ данных': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Data_O.xlsx',
        'Программа двух дипломов НИУ ВШЭ и Университета Кёнхи "Экономика и политика Азии" (Зарубежное регионоведение)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_epa27_O.xlsx',
        'Программа двух дипломов НИУ ВШЭ и Университета Кёнхи "Экономика и политика Азии" (Публичная политика и социальные науки)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_epa29_O.xlsx',
        'Программная инженерия': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_SE_O.xlsx',
        'Психология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Psy_O.xlsx',
        'Реклама и связи с общественностью': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_AD_O.xlsx',
        'Реклама и связи с общественностью (Медиакоммуникации)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ADM_O.xlsx',
        'Совместная программа по экономике НИУ ВШЭ и РЭШ': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_RESH_O.xlsx',
        'Совместный бакалавриат НИУ ВШЭ и Центра педагогического мастерства': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_CPM_O.xlsx',
        'Современное искусство': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Art_O.xlsx',
        'Социология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Soc_O.xlsx',
        'Стратегия и продюсирование в коммуникациях': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Producer_O.xlsx',
        'Управление бизнесом': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_BBA_O.xlsx',
        'Управление в креативных индустриях': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Creative_O.xlsx',
        'Управление цепями поставок и бизнес-аналитика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Logistics_O.xlsx',
        'Управление цифровым продуктом': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Digital_O.xlsx',
        'Физика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Physics_O.xlsx',
        'Филология': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Philology_O.xlsx',
        'Философия': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Phil_O.xlsx',
        'Фундаментальная и компьютерная лингвистика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_FKL_O.xlsx',
        'Химия': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Chem_O.xlsx',
        'Экономика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Economy_O.xlsx',
        'Экономика и анализ данных': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_EcAl_O.xlsx',
        'Экономика и статистика': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Stat_O.xlsx',
        'Экономический анализ': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_EA_O.xlsx',
        'Юго-Восточная Азия: языки, история, культуры': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Asia_O.xlsx',
        'Юриспруденция': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_LAW_O.xlsx',
        'Юриспруденция: правовое регулирование бизнеса (очно-заочная форма обучения)': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Doplaw_OZ.xlsx',
        'Юриспруденция: цифровой юрист': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Dlawyer_O.xlsx',
        'Япония: язык, история, литература, культура': 'https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Japanese_O.xlsx'
    },
    'санкт-петербург': {
        'Аналитика в экономике': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Ave_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_MBBE_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике (целевой прием по направлению 38.03.01 Экономика)': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_MBBE_E_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике (целевой прием по направлению 38.03.02 Менеджмент)': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_MBBE_M_O.xlsx',
        'Бизнес-информатика': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_BI_O.xlsx',
        'Востоковедение': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Vostok_O.xlsx',
        'Дизайн': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Design_O.xlsx',
        'История': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_ISTR_O.xlsx',
        'Компьютерные технологии, системы и сети': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_KNT_SysNet_O.xlsx',
        'Медиакоммуникации': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Media_O.xlsx',
        'Политология и мировая политика': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_PMP_O.xlsx',
        'Прикладная математика и информатика': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_AMI_O.xlsx',
        'Прикладной анализ данных и искусственный интеллект': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_PADII_O.xlsx',
        'Социология и социальная информатика': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Socci_O.xlsx',
        'Управление бизнесом': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_BBA_O.xlsx',
        'Управление и аналитика в государственном секторе': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_GMU_O.xlsx',
        'Физика': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Physics_O.xlsx',
        'Филология': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_Philology_O.xlsx',
        'Юриспруденция': 'https://enrol.hse.ru/storage/public_report_2024/spb/Bachelors/BD_spb_LAW_O.xlsx'
    },
    'нижний новгород': {
        'Дизайн': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_Design_O.xlsx',
        'Иностранные языки и межкультурная бизнес-коммуникация': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_IYAMK_O.xlsx',
        'Компьютерные науки и технологии (Бизнес-информатика)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_KNT_BI_O.xlsx',
        'Компьютерные науки и технологии (Прикладная математика и информатика)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_KNT_AMI_O.xlsx',
        'Компьютерные науки и технологии (Программная инженерия)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_KNT_SE_O.xlsx',
        'Математика': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_Math_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_MBBE_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике (целевой прием по направлению 38.03.01 Экономика)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_MBBE_E_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике (целевой прием по направлению 38.03.02 Менеджмент)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_MBBE_M_O.xlsx',
        'Программная инженерия (очно-заочная форма обучения)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_SE_OZ.xlsx',
        'Технологии искусственного и дополненного интеллекта': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_Ait_O.xlsx',
        'Филология': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_Philology_O.xlsx',
        'Фундаментальная и прикладная лингвистика': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_Ling_O.xlsx',
        'Цифровой маркетинг': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_DM_O.xlsx',
        'Юриспруденция': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_LAW_O.xlsx',
        'Экономика и бизнес (очно-заочная форма обучения)': 'https://enrol.hse.ru/storage/public_report_2024/nn/Bachelors/BD_nn_Economics_OZ.xlsx'
    },
    'пермь': {
        'Дизайн': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_Design_O.xlsx',
        'Иностранные языки и межкультурная коммуникация в бизнесе': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_IYAMK_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_MBBE_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике (целевой прием по направлению 38.03.01 Экономика)': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_MBBE_E_O.xlsx',
        'Международный бакалавриат по бизнесу и экономике (целевой прием по направлению 38.03.02 Менеджмент)': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_MBBE_M_O.xlsx',
        'Программные системы и автоматизация процессов разработки': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_ssadp_O.xlsx',
        'Разработка информационных систем для бизнеса (Бизнес-информатика)': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_IsystemsB_O.xlsx',
        'Разработка информационных систем для бизнеса (Программная инженерия)': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_IsystemsP_O.xlsx',
        'Управление бизнесом (очно-заочная форма обучения)': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_BBA_OZ.xlsx',
        'Юриспруденция': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_LAW_O.xlsx',
        'Юриспруденция (очно-заочная форма обучения)': 'https://enrol.hse.ru/storage/public_report_2024/perm/Bachelors/BD_perm_LAW_OZ.xlsx'
    }
}


def get_hse_programs(city):
    return list(hse_programs.get(city.lower(), {}).keys())


def get_hse_program_url(city, program):
    return hse_programs.get(city.lower(), {}).get(program)
