name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send webhook to server      
      run: |
        curl -X POST http://91.224.87.231:13723/webhook-endpoint
